### ISSUE TITLE
Add 6to5 Support

### ISSUE THREAD

**Issue by darcyclarke** [richgilbank/ES6-Repl-Chrome-Extension#17]
Work to add 6to5 support through a toggle or button. Would love this option and have referenced so in [here](https://github.com/6to5/6to5-browser-extension/issues/1).

**Comment by richgilbank** [comment]
Working branch: https://github.com/richgilbank/ES6-Repl-Chrome-Extension/compare/6to5?expand=1

**Comment by hemanth** [comment]
@richgilbank Let me know if I can be of any help, thanks.

**Comment by richgilbank** [comment]
I've made some good progress on this but have encountered [this Chromium bug](https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=178618) in DevTools, which is a bit of a hassle. Was using chrome storage to save preferences on which transpiler to use; will have to find a workaround since this bug's been open long enough to not expect it to be resolved any time soon. Shouldn't take long. 

@hemanth Thanks! Can always use help. I'm going to just try to get this to a point where I can merge it in, but from there there are a number of things to be done. You expressed interest before in working on a build system, which will most definitely be needed (things are growing too big to not have one now). My working branch also includes a settings panel, so we can start adding configurable settings for 6to5/Traceur, which would be another good project to work on. Will ping you once I've got this foundation stuff in place.
